version: "3"
services:
  app:
    image: node:18
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: >
      bash -c "npm install &&
               npm run dev"
    tty: true
    stdin_open: true
    user: node
    depends_on:
      - shopper_db
  shopper_db:
    image: mysql:8.0
    container_name: shopper_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shopper_db
      MYSQL_USER: shopper_user
      MYSQL_PASSWORD: shopper_password
    ports:
      - "3307:3306"
    volumes:
      - shopper_db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  shopper_db_data:
