version: "3"
services:
  app:
    image: node:18
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: bash
    tty: true
    stdin_open: true
    user: node
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"